#微服务端口号
server:
  port: 8002

spring:
  application:  #微服务名
    name: microservice-payment-service                        #向外提供的微服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource             # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud?characterEncoding=utf8&serverTimezone=GMT&useSSL=false             # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

#入驻
eureka:
  client:
    #registerWithEureka: true #表示入驻rureka
    register_with_eure: true
    fetchRegistry: true #是否从Eureka上抓取已有的注册信息，默认为true，单节点无所谓，但是集群配置必须设为true才能配合ribbon实现负载均衡
    service-url:
      #defaultZone: http://localhost:7001/eureka  #入驻到服务注册
      defaultZoone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #入驻集群
  instance:
    instance-id: microservice-payment8002
    prefer-ip-address: true #访问路径显示IP

#mybaits相关
mybatis:
  config-location: classpath:mybatis/mybatis.config.xml        # mybatis配置文件所在路径
  type-aliases-package: com.chinaedu.springcloud.entity        # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件