server:
  port: 80

#服务名称
spring:
  application:
    name: microservice-order-feign-service

#入驻
eureka:
  client:
    register-with-eureka: false #表示入驻rureka
    #register-with-eureka: false #表示不入驻rureka
    fetch-registry: false #是否从Eureka上抓取已有的注册信息，默认为true，单节点无所谓，但是集群配置必须设为true才能配合ribbon实现负载均衡
    service-url:
      #defaultZone: http://localhost:7001/eureka  #入驻到服务注册
      defaultZoone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #入驻集群

#修改OpenFeign默认等待时间
ribbon:
  ReadTimeout: 5000   #建立连接所用时间，适用于网络状况正常情况下，两端连接所用时间
  ConnectTimeOut: 5000 #建立连接后从服务读取到可用资源的时间

#日志
logging:
  level:
    com.chinaedu.springcloud.service.PaymentFeignSerevice : debug #feign日志以什么级别监控接口
