server:
  port: 9529

spring:
  application:
    name: microservice-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从服务注册中心动态创建路由的功能，利用微服务名进行路由跳转
      routes:
        - id: payment_routh #payment_router  #路由id,没有固定的规则但是必须唯一，建议配合服务名
          #url: http://localhost:8001  #匹配后提供服务的路由地址
          url: lb://microservice-payment-service #匹配后提供服务的路由地址 lb:负载均衡
          predicates:
            - Path = /payment/get/**  #断言，路径匹配的进行路由
            #ZonedDateTime zonedDateTime = ZonedDateTime.now(); //获得默认时区时间
            #当且仅当请求时的时间After配置的时间时，才会转发到用户微服务
            #当前时间为19:19:00 不会进该路由配置，所以返回404
            - After = 2020-07-06T19:20:35.665+08:00[Asia/Shanghai]

        - id: payment_routh2
          #url: http://localhost:8001  #匹配后提供服务的路由地址
          url: lb://microservice-payment-service #匹配后提供服务的路由地址  lb:负载均衡
          predicates:
            - Path = /payment/findAll/**  #断言，路径匹配的进行路由

        - id: payment_routh3
            #url: http://localhost:8001  #匹配后提供服务的路由地址
            url: lb://microservice-payment-service #匹配后提供服务的路由地址 lb:负载均衡
            predicates:
              - Path = /payment/lb/**  #断言，路径匹配的进行路由

#注册进服务中心
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-register: true
      defaultZone: http://eureka7001.com:7001/eureka