#服务端口号，表示注册到zookeeper服务器的支付服务提供者的端口号
server:
  port: 8005

#服务别名----注册到zookeeper中心的名称
spring:
  application:
    name: microservice-provider-payment
  cloud:
    zookeeper:
      connect-string: 192.168.10.3:2181
