#服务端口号，表示注册到zookeeper服务器的支付服务提供者的端口号
server:
  port: 80

#服务别名----注册到zookeeper中心的名称
spring:
  application:
    name: microservice-client-order
  cloud:
    zookeeper:
      connect-string: 192.168.10.3:2181  #zookeeper ip:端口号