server:
  port: 9401

spring:
  application:
    name: microservice-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhsot://8848  #注册进nacos中心
    sentinel:
       #配置sentinel dashbord地址
       transport:
         dashboard: localhost:8080
         port: 8719  #默认8719端口，如果被占用则会自动从8719开始依次加1，直到找到未被占用的端口
         datasource:
                ds1:
                  nacos:
                    server-addr: localhost:8848
                    dataID: microservice-sentinel-service
                    groupId: Default_Group
                    data-type: json
                    rule-type: flow

management:
    endpoints:
       web:
         exposure:
           include: "*"
feign:
  sentinel:
    enabled: true
